### PR TITLE
Jakarta spec fixes in pom

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by arjantijms** [comment]
@m0mus 
With 1.5 I'm getting the following peculiar message:

```
[INFO] --- spec-version-maven-plugin:1.5:check-module (default) @ jakarta.security.auth.message-api ---

[ jakarta.security.auth.message:jakarta.security.auth.message-api:1.1.2-SNAPSHOT ]
{ groupIdPrefix=jakarta. spec-version=1.1 apiPackage=jakarta.security.auth.message API final spec-impl-version=1.1.2 }
- WARNING: API packages (jakarta.security.auth.message) must start with "jakarta."
```

**Comment by m0mus** [comment]
@arjantijms Change `apiPackage` parameter in spec-version plugin configuration to the valid **package** name, which is `javax.security.auth.message`

```
<apiPackage>javax.security.auth.message</apiPackage>
```

**Comment by arjantijms** [comment]
@m0mus Super, thx! I was indeed confused what to put there. I just pushed the changes.

**Comment by m0mus** [comment]
@arjantijms Great! No you should merge it into EE4J_8 branch.

**Pull request merged**
